packages:
  - 'goblin'
  - 'gringotts'
  - 'idp'
  - 'linkmgr'
  - 'linkproc'
  - 'mailman'
  - 'tacklebox'
  - 'tbdev'
  - 'tbdev-queue-consumer'
  - 'tbdev-do'
  - 'tbdev-workflow'
  - 'tbdev-rpc'
  - 'tbdev-tail'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
